# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'
#Bypassing Vagrant Cloud blocking in Russia
ENV['VAGRANT_SERVER_URL'] = 'https://vagrant.elab.pro'

Vagrant.configure("2") do |config|
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "AnsibleTest.yml"
  end
  config.vm.define "Debian11_VM" do |vm_conf|
    vm_conf.vm.box = "debian/bullseye64"
    vm_conf.vm.provider "virtualbox" do |vb|
      vb.name = "VagrantVM"
      vb.gui = false
      vb.memory = 1024
      vb.cpus = 1
    end
  end
end
